/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arayuz;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.collections.ObservableList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sınıflar.calisanlar;
import sınıflar.kayitlar;
import sınıflar.listeleme;

/**
 *
 * @author oktay
 */
public class form3a extends javax.swing.JFrame {

    /**
     * Creates new form form3
     */
    public form3a() {
        initComponents();
        setTitle("İzin Listeleme");
        setSize(1080,700);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,
		size.height/2 - getHeight()/2);
        
        
        
        try {
          ArrayList<calisanlar> sonuc=new calisanlar().cListele();
            DefaultTableModel tab= (DefaultTableModel) tablo1.getModel();
                    tab.getDataVector().clear();
            tablo1.repaint();
        Vector [] v= new Vector[sonuc.size()];
        for (int i = 0; i < sonuc.size(); i++) {
            v[i]=new Vector();
            v[i].add(sonuc.get(i).getCalisan_id());
            v[i].add(sonuc.get(i).getTc_no());
            v[i].add(sonuc.get(i).getSicil_no());
            v[i].add(sonuc.get(i).getAd());
            v[i].add(sonuc.get(i).getSoyad());
            v[i].add(sonuc.get(i).getBirim());
            v[i].add(sonuc.get(i).getCinsiyet());
            v[i].add(sonuc.get(i).getDogum_tarihi());
            v[i].add(sonuc.get(i).getSehir());
            tab.insertRow(i, v[i]);  
        }
        }catch (SQLException ex) {
            Logger.getLogger(form3a.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablo2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        tablo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Calisan id", "Tc No", "Sicil No", "Ad", "Soyad", "Birim", "Cinsiyet", "Dogum Tarihi", "Sehir"
            }
        ));
        tablo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablo1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablo1MousePressed(evt);
            }
        });
        tablo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablo1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablo1);

        tablo2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kayit No", "Calisan No", "İzin Türü", "Baslangıc Tarihi", "Bitis Tarihi", "Izin Süresi"
            }
        ));
        jScrollPane2.setViewportView(tablo2);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setDisplayedMnemonic('\u0014');
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Calisanlar");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("İzinler");

        jButton1.setText("İzin Sil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(483, 483, 483)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(487, 487, 487)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(113, 113, 113))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablo1MousePressed
      try {
        String calisan_id = tablo1.getValueAt(tablo1.getSelectedRow(), 0).toString();
        ObservableList<kayitlar> sonuc = new listeleme().listele(calisan_id);
        DefaultTableModel tab= (DefaultTableModel) tablo2.getModel();
        tab.getDataVector().clear();
        tablo2.repaint();
        Vector [] v= new Vector[sonuc.size()];
        for (int i = 0; i < sonuc.size(); i++) {
            v[i]=new Vector();
            v[i].add(sonuc.get(i).getKayit_id());
            v[i].add(sonuc.get(i).getCalisan_id());
            v[i].add(sonuc.get(i).getIzin_tur());
            v[i].add(sonuc.get(i).getBaslangıc());
            v[i].add(sonuc.get(i).getBitis());
            v[i].add(sonuc.get(i).getSure());
            tab.insertRow(i, v[i]);
        }
        } catch (Exception e) {
            System.out.println(e);
        }
        
            

    }//GEN-LAST:event_tablo1MousePressed

    private void tablo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablo1MouseClicked

    private void tablo1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablo1KeyPressed
        // TODO add your handling code here:
        try {
        String sicil_no = tablo1.getValueAt(tablo1.getSelectedRow(), 0).toString();
        ObservableList<kayitlar> sonuc = new listeleme().listele(sicil_no);
        DefaultTableModel tab= (DefaultTableModel) tablo2.getModel();
        tab.getDataVector().clear();
        tablo2.repaint();
        Vector [] v= new Vector[sonuc.size()];
        for (int i = 0; i < sonuc.size(); i++) {
            v[i]=new Vector();
            v[i].add(sonuc.get(i).getKayit_id());
            v[i].add(sonuc.get(i).getCalisan_id());
            v[i].add(sonuc.get(i).getIzin_tur());
            v[i].add(sonuc.get(i).getBaslangıc());
            v[i].add(sonuc.get(i).getBitis());
            v[i].add(sonuc.get(i).getSure());
            tab.insertRow(i, v[i]);
        }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_tablo1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean silKontrol=false;
        kayitlar ks = new kayitlar(); 
        ks.setKayit_id(null);
        ks.setCalisan_id(null);
        ks.setIzin_tur(null);
        ks.setBaslangıc(null);
        ks.setBitis(null);
        ks.setSure(null);
            
        if(JOptionPane.showConfirmDialog(null, "Silmek İstediğinize emin misiniz?",
                "Dikkat", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            silKontrol = ks.kayitSil(tablo2.getValueAt(tablo2.getSelectedRow(), 0).toString());
            
        }
        if(silKontrol){
            JOptionPane.showMessageDialog(null, "Silindi");
            
        }
        try {
        String sicil_no = tablo1.getValueAt(tablo1.getSelectedRow(), 0).toString();
        ObservableList<kayitlar> sonuc = new listeleme().listele(sicil_no);
        DefaultTableModel tab= (DefaultTableModel) tablo2.getModel();
        tab.getDataVector().clear();
        tablo2.repaint();
        Vector [] v= new Vector[sonuc.size()];
        for (int i = 0; i < sonuc.size(); i++) {
            v[i]=new Vector();
            v[i].add(sonuc.get(i).getKayit_id());
            v[i].add(sonuc.get(i).getCalisan_id());
            v[i].add(sonuc.get(i).getIzin_tur());
            v[i].add(sonuc.get(i).getBaslangıc());
            v[i].add(sonuc.get(i).getBitis());
            v[i].add(sonuc.get(i).getSure());
            tab.insertRow(i, v[i]);
        }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form3a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form3a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form3a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form3a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form3a().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablo1;
    private javax.swing.JTable tablo2;
    // End of variables declaration//GEN-END:variables
}
